"BEAU GOTO LINE 31 FOR PLUGINS
set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git BEAU NOTE this is not working
"there is a ruby version symlink issue
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}
" 
"BEAU PLUGINS
Plugin 'vim-airline/vim-airline' "FROM HERE https://oracleyue.github.io/2019/11/07/vim-powerline/
Plugin 'vim-airline/vim-airline-themes' "FROM HERE https://github.com/vim-airline/vim-airline-themes Once installed, use :AirlineTheme <theme> to set the theme, e.g. :AirlineTheme simple CURRENTLY USING
let g:airline_theme='minimalist'
Plugin 'ryanoasis/vim-devicons' "Dev icons for vim plugins
Plugin 'https://github.com/ycm-core/YouCompleteMe.git' "Autocompletion - using for java
"Disabling YCM preview window they displays up the top
set completeopt-=preview
"Disabling Syntastic think it was causing issues with java files for now
"Plugin 'https://github.com/vim-syntastic/syntastic.git' "Syntax highlighting
"Plugin 'preservim/nerdtree' "Adds file system tree - if you want it = D NOTE:
"Disabled this based on advice from https://shapeshed.com/vim-netrw/ - trying
"netrw instead - less dependencies
Plugin 'junegunn/fzf', { 'do': './install --bin' } "ensures we have most recent binaries for fzf
Plugin 'junegunn/fzf.vim' "https://github.com/junegunn/fzf.vim SEE HERE FOR MORE DETAILS

"Markdown Support for Joplin CLI
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

"Vim auto- autocorrect uses vim 'spell' automagically
Plugin 'sedm0784/vim-you-autocorrect'

"CURRENT THEME CONFIG OPTIONS
Plugin 'https://github.com/tomasr/molokai.git' "Molokai Theme"

" Ale linter extension
Plugin 'dense-analysis/ale'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line


" System vimrc file for MacVim
"
" Author:       Bjorn Winckler <bjorn.winckler@gmail.com>
" Maintainer:   macvim-dev (https://github.com/macvim-dev)

"set nocompatible we have already set this above

" the entire MacVim menu is set up in a nib file which currently only is
" translated to English).
set langmenu=none

" Python2
" MacVim is configured by default to use the pre-installed System python2
" version. However, following code tries to find a Homebrew, MacPorts or
" an installation from python.org:
if exists("&pythondll") && exists("&pythonhome")
  if filereadable("/usr/local/Frameworks/Python.framework/Versions/2.7/Python")
    " Homebrew python 2.7
    set pythondll=/usr/local/Frameworks/Python.framework/Versions/2.7/Python
  elseif filereadable("/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Python")
    " MacPorts python 2.7
    set pythondll=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Python
  elseif filereadable("/Library/Frameworks/Python.framework/Versions/2.7/Python")
    " https://www.python.org/downloads/mac-osx/
    set pythondll=/Library/Frameworks/Python.framework/Versions/2.7/Python
  endif
endif

" Python3
" MacVim is configured by default to use Homebrew python3 version
" If this cannot be found, following code tries to find a MacPorts
" or an installation from python.org:
if exists("&pythonthreedll") && exists("&pythonthreehome") &&
      \ !filereadable(&pythonthreedll)
  if filereadable("/opt/local/Library/Frameworks/Python.framework/Versions/3.7/Python")
    " MacPorts python 3.7
    set pythonthreedll=/opt/local/Library/Frameworks/Python.framework/Versions/3.7/Python
  elseif filereadable("/Library/Frameworks/Python.framework/Versions/3.7/Python")
    " https://www.python.org/downloads/mac-osx/
    set pythonthreedll=/Library/Frameworks/Python.framework/Versions/3.7/Python
  endif
endif

"BEAU CONFIGS
set autoindent "enable auto-indentation"
set smartindent  " smart  autoindent (e.g. add indent after '{')
syntax on  "enable syntax highlighting"
set number "enable line numbers"
set softtabstop=4 "option so make backspace delete entire tab"
set tabstop=4 "setting tab to 4 spaces"
set expandtab "this feature means that tabs are actually whitespaces so when we send code to friend indentation is not messed up"
set cursorline "enable line under cursor"
let skip_defaults_vim=1
set incsearch "search as characters are entered"
set hlsearch "highlight matches"
set backspace=indent,eol,start " this makes backspace work as normal
"note for future me, perhaps you can try folding, its lets you collapse code down like a project sidebar viwer type thing would."
filetype plugin indent on "this enables It detection, plugin and indent at once"
set encoding=UTF-8 "REQUIRED BY DEV ICONS PLUGIN

"hopefully this speeds up vim!
set lazyredraw

"THEME CONFIG
colorscheme molokai
set termguicolors "enabling terminal color support
set t_Co=256 "enabling 256 color support
let g:rehash256 = 1 "enabling 256 support for molokai

"BEAU New configs still under testing
set wildmenu "enables visual autocomplete for vim command NOTE, use tab to enable
"BEAU - making vim autocomplete more bash like - NOTE there is an option
"<full> which prints a full list, not really a fan as it confuses me too much
"text on screen and lose my flow
set wildmode=list,full


set autochdir "sets the cwd to whatever file is in view. This allows better ommicompletion

"FZF Vim config
"set rtp+=/usr/local/opt/fzf

nmap e $
nmap s 0
nmap ; :
"NO MORE SHIFT KEY :D
"
"adding autoclosing brackets map
inoremap { {}<left>
