local function init()
	require('libraries._module')
	safe_require('core.init')
	safe_require('plugins._lazy')
	--safe_require('settings._optimisations')
	safe_require('settings._options')
	safe_require('settings.mappings.init')
	safe_require('settings.commands.init')
	safe_require('settings.lsp.init')
	safe_require('settings._autocmds')
	safe_require('settings._abbreviations')
	safe_require('settings._theme')
	--  safe_require("plugins._plugins")
	--  safe_require("plugins._statusline")
	--  safe_require("plugins._cmp")
	--  safe_require("plugins._mason")
	--  safe_require("plugins._startify")
	--  safe_require("plugins._telescope")
	--  safe_require("plugins._treesitter")
	--  safe_require("plugins._my_terminal")
	--  safe_require("plugins._my_highlight_cursor")
	--  safe_require("plugins._nvimtree")
	--  safe_require("plugins._discord")
	--  safe_require("plugins._goto-preview")
	--  safe_require("plugins._nvim-notify")
	--  safe_require("plugins._hydra")
	--  safe_require("plugins._aerial")
	--  safe_require("plugins._symbols-outline")
	--  safe_require("plugins._dial")
	--  safe_require("plugins._noice")
	--  safe_require("lsp._lsp_config")
	return nil
end
init()
return nil
