iabbrev <buffer> github GitHub
iabbrev <buffer> gitub GitHub
iabbrev <buffer> ansible Ansible
iabbrev <buffer> jenkins Jenkins
iabbrev <buffer> google Google
iabbrev <buffer> aws AWS
iabbrev <buffer> azure Azure
iabbrev <buffer> cms CMS
iabbrev <buffer> k8s K8s
iabbrev <buffer> linux Linux
iabbrev <buffer> influxdb InfluxDB
iabbrev <buffer> javascript JavaScript
iabbrev <buffer> typescript TypeScript
